### ISSUE TITLE
Unable to generate libdoc because of circular dependency in Python install files

### ISSUE THREAD

**Issue by solomon2530** [rasjani/robotframework-seleniumtestability#56]
I was trying to generate the libdoc for SeleniumTestability using the following command in Command Line:
**python -m robot.libdoc SeleniumLibrary::plugins=SeleniumTestability**

However, it ends in an error message as follows:

Could not import runpy module
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 57, in <module>
    import types
  File "C:\Program Files\Python39\Lib\site-packages\SeleniumTestability\types.py", line 2, in <module>
    from typing import Union, Optional, List, Dict
  File "C:\Program Files\Python39\lib\typing.py", line 23, in <module>
    import contextlib
  File "C:\Program Files\Python39\lib\contextlib.py", line 6, in <module>
    from functools import wraps
  File "C:\Program Files\Python39\lib\functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (C:\Program Files\Python39\Lib\site-packages\SeleniumTestability\types.py)

Any ideas on how to fix this?

**Comment by rasjani** [comment]
Which robotframework version are you using ? There has been changes on how RF creates docs so, this could be because of those changes ..

**Comment by solomon2530** [comment]
I have been using the following:
Robot Framework (v 3.2.2)
SeleniumLibrary (v 5.0.0)

I did eventually manage to generate the libdoc by changing the path of installation to one containing all the files mentioned in the error message i.e. C:\Program Files\Python39\lib

Not very sure how this resolved the cyclic import issue.

Consider this issue closed.
